"""Add review workflow enhancements with assignments and reviewer roles

Revision ID: 0942d2b782e2
Revises: 0de046203226
Create Date: 2025-07-01 18:18:40.417807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0942d2b782e2'
down_revision: Union[str, Sequence[str], None] = '0de046203226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feedback', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feedback', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'users', ['reviewed_by'], ['id'])
    op.add_column('review_sessions', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('review_sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('review_sessions', sa.Column('reviewer_id', sa.Integer(), nullable=False))
    op.add_column('review_sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('review_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_sessions', sa.Column('target_completion_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('review_sessions_user_id_fkey'), 'review_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'review_sessions', 'users', ['reviewer_id'], ['id'])
    op.drop_column('review_sessions', 'user_id')
    op.drop_column('review_sessions', 'timestamp')
    op.add_column('users', sa.Column('reviewer_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'reviewer_level')
    op.add_column('review_sessions', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('review_sessions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('review_sessions_user_id_fkey'), 'review_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('review_sessions', 'target_completion_date')
    op.drop_column('review_sessions', 'completed_at')
    op.drop_column('review_sessions', 'created_at')
    op.drop_column('review_sessions', 'reviewer_id')
    op.drop_column('review_sessions', 'description')
    op.drop_column('review_sessions', 'name')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'reviewed_by')
    op.drop_column('feedback', 'reviewed_at')
    op.drop_column('feedback', 'review_notes')
    op.drop_table('review_assignments')
    # ### end Alembic commands ###
