"""Add voice notes tables for audio feedback integration

Revision ID: 0de046203226
Revises: 88508e0133e5
Create Date: 2025-07-01 18:12:42.475516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de046203226'
down_revision: Union[str, Sequence[str], None] = '88508e0133e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('audio_format', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=True),
    sa.Column('cloud_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_note_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('whisper_model', sa.String(length=20), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['voice_note_id'], ['voice_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_enhanced_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_note_id', sa.Integer(), nullable=False),
    sa.Column('original_suggestion_id', sa.Integer(), nullable=True),
    sa.Column('voice_context', sa.Text(), nullable=False),
    sa.Column('enhanced_suggestion', sa.Text(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['original_suggestion_id'], ['chatgpt_interactions.id'], ),
    sa.ForeignKeyConstraint(['voice_note_id'], ['voice_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_enhanced_suggestions')
    op.drop_table('transcriptions')
    op.drop_table('voice_notes')
    # ### end Alembic commands ###
